### ISSUE TITLE
Same request is repeated when refreshing after adding products

### ISSUE THREAD

**Issue by Engineering-Excellence** [KOSA-PCMASTER/PCMASTER#80]
- Due to the phenomenon of the URL being maintained after adding products and images
- The same request is repeated when refreshing

**Comment by bnbu** [comment]
The problem caused by line 63 in ProductController.java.

`response.sendRedirect("product/list");`

When sendRedirect's parameter(location) is start without '/', it means relative location.

product insert page's request URL is (Domain)/product/insert and in this moment reponse's URL is (Domatin)/product. therefore sendRedirect make URL to (Domain)/product/product/list

And we can fix it to `response.sendRedirect("/product/list");`

the location start with '/' means  absolute location.
so sendRedirect can make URL start from root, it will be (Domain)/product/list

as same as we can fix it to `response.sendRedirect("../product/list");`.
